# Work with Secrets
SECRET_SUPER_SECRET

# This is a basic workflow to help you get started with Actions

name: deploy.yml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - name: run deploy
    shell: bash    
  run: |
    echo "show env"
    echo "SHow secret"
